---
- hosts: all
  become: yes
  tasks:
          - name: install vsftpd and tree
            apt: name= "{{ item }}" state=present update_cache=true
            with_items: 
               - 'vsftpd'
               - 'tree' 
 
